# Generated by Django 5.0.3 on 2024-03-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
            ],
        ),
    ]
