# Generated by Django 5.0.3 on 2024-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actors',
            field=models.ManyToManyField(to='films.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='films.genre'),
        ),
    ]
